sudo: required

services:
    - docker

language: php

cache:
    directories:
        - vendor

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: CONFIG="phpunit-integration.xml" COVERAGE="all"

branches:
    only:
        - master

before_install:
    - docker build --file ./.docker/elasticsearch/Dockerfile --tag elasticsearch .
    - docker run --detach --publish 9200:9200 elasticsearch
    - ./bin/wait_for_server.sh
    - phpenv config-add travis.php.ini

install:
    - travis_wait composer install

script:
    - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c $CONFIG --coverage-clover=coverage.xml

notification:
    email: false

git:
    depth: 30

after_success:
    - bash <(curl -s https://codecov.io/bash) -F $COVERAGE
