sudo: required

services:
    - docker

language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 7.2
          env: CONFIG="phpunit-integration.xml" COVERAGE="all"

# test only master and pull requests to master
branches:
    only:
        - master

before_install:
    - docker build --file ./.docker/elasticsearch/Dockerfile --tag elasticsearch .
    - docker run --detach --publish 9200:9200 elasticsearch
    - ./bin/wait_for_server.sh
    - phpenv config-add travis.php.ini

# install dependencies
install:
    - travis_wait composer install

# execute phpunit as the script command
script:
    - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c $CONFIG --coverage-clover=coverage.xml

# disable mail notifications
notification:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30

# send coverage to https://codecov.io
after_success:
    - bash <(curl -s https://codecov.io/bash) -F $COVERAGE
