sudo: required

services:
    - docker

language: php

cache:
    directories:
        - vendor

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: CONFIG="phpunit.xml" COVERAGE="all"

branches:
    only:
        - master

before_install:
    - docker-compose -f ./config/.docker/docker-compose.travis.yml up --build -d
    - docker ps -a
    - ./bin/wait_for_server.sh
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - travis_wait composer install

script:
    - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c $CONFIG --coverage-clover=coverage.xml --testdox

notification:
    email: false

git:
    depth: 30

after_success:
    - bash <(curl -s https://codecov.io/bash) -F $COVERAGE
