version: '3.3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        container_name: elasticsearch0
        environment:
            - node.name=elasticsearch0
            - cluster.name=cabbage
            - cluster.initial_master_nodes=elasticsearch0
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - network.host=_eth0_
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
            - ALL
        networks:
            - elastic
        ports:
            - 9200:9200
            - 9300:9300
    elasticsearch1:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        container_name: elasticsearch1
        environment:
            - node.name=elasticsearch1
            - cluster.name=cabbage
            - cluster.initial_master_nodes=elasticsearch0
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
            - "discovery.zen.ping.unicast.hosts=elasticsearch0"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - network.host=_eth0_
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
            - ALL
        networks:
            - elastic
        ports:
            - 9201:9200
    elasticsearch2:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        container_name: elasticsearch2
        environment:
            - node.name=elasticsearch2
            - cluster.name=cabbage
            - cluster.initial_master_nodes=elasticsearch0
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
            - "discovery.zen.ping.unicast.hosts=elasticsearch0"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - network.host=_eth0_
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
            - ALL
        networks:
            - elastic
        ports:
            - 9202:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.1
        container_name: kibana
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch0:9200/
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
            - ALL
        networks:
            - elastic
        ports:
            - 5601:5601
networks:
    elastic:
