version: '3'
services:
    elasticsearch:
        build:
            context: .
            dockerfile: ./elasticsearch/Dockerfile
        restart: on-failure:3
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
    kibana:
        build:
            context: .
            dockerfile: ./kibana/Dockerfile
        restart: on-failure:3
        container_name: kibana
        links:
            - elasticsearch
        ports:
            - "5601:5601"
