FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.0-alpha2

ENV discovery.type single-node
ENV http.host 0.0.0.0
ENV transport.host 127.0.0.1
ENV xpack.security.enabled false
ENV ES_JAVA_OPTS "-Xms750m -Xmx750m"
