services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.gateway:
        class: Cabbage\Core\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.document_mapper:
        class: Cabbage\DocumentMapper
        arguments:
            - '@ezpublish.spi.persistence.location_handler'

    cabbage.document_router:
        class: Cabbage\DocumentRouter

    cabbage.document_serializer:
        class: Cabbage\DocumentSerializer

    cabbage.document_bulk_serializer:
        class: Cabbage\DocumentBulkSerializer
        arguments:
            - '@cabbage.document_router'
            - '@cabbage.document_serializer'

    cabbage.query_translator:
        class: Cabbage\Core\Query\Translator

    cabbage.query_router:
        class: Cabbage\Core\Query\Router

    cabbage.result_extractor:
        class: Cabbage\Core\ResultExtractor

    cabbage.handler:
        class: Cabbage\Core\Handler
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document_mapper'
            - '@cabbage.document_bulk_serializer'
            - '@cabbage.query_translator'
            - '@cabbage.query_router'
            - '@cabbage.result_extractor'
