services:
    cabbage.http.client:
        class: Cabbage\Http\Client

    cabbage.document_serializer:
        class: Cabbage\DocumentSerializer

    cabbage.gateway:
        class: Cabbage\Gateway
        arguments:
            - '@cabbage.http.client'
            - '@cabbage.document_serializer'

    cabbage.document_mapper:
        class: Cabbage\DocumentMapper

    cabbage.document_router:
        class: Cabbage\DocumentRouter

    cabbage.query_translator:
        class: Cabbage\QueryTranslator

    cabbage.query_router:
        class: Cabbage\QueryRouter

    cabbage.result_extractor:
        class: Cabbage\ResultExtractor

    cabbage.handler:
        class: Cabbage\Handler
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document_mapper'
            - '@cabbage.document_router'
            - '@cabbage.query_translator'
            - '@cabbage.query_router'
            - '@cabbage.result_extractor'
