services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.gateway:
        class: Cabbage\Core\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.document_mapper:
        class: Cabbage\Core\Document\Mapper
        arguments:
            - '@ezpublish.spi.persistence.location_handler'

    cabbage.document_router:
        class: Cabbage\Core\Document\Router

    cabbage.field_value_mapper:
        class: Cabbage\Core\Document\FieldValueMapper

    cabbage.field_name_generator:
        class: Cabbage\Core\Document\FieldNameGenerator

    cabbage.document_serializer:
        class: Cabbage\Core\Document\Serializer
        arguments:
            - '@cabbage.field_name_generator'
            - '@cabbage.field_value_mapper'

    cabbage.document_bulk_serializer:
        class: Cabbage\Core\Document\BulkSerializer
        arguments:
            - '@cabbage.document_router'
            - '@cabbage.document_serializer'

    cabbage.query_translator.criterion_visitor.custom_field:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\CustomField

    cabbage.query_translator.criterion_visitor.document_type:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\DocumentType

    cabbage.query_translator.criterion_visitor_dispatcher:
        class: Cabbage\Core\Query\Translator\Criterion\VisitorDispatcher
        arguments:
            -
                - '@cabbage.query_translator.criterion_visitor.custom_field'
                - '@cabbage.query_translator.criterion_visitor.document_type'

    cabbage.query_translator:
        class: Cabbage\Core\Query\Translator
        arguments:
            - '@cabbage.query_translator.criterion_visitor_dispatcher'

    cabbage.query_router:
        class: Cabbage\Core\Query\Router

    cabbage.result_extractor:
        class: Cabbage\Core\ResultExtractor

    cabbage.handler:
        class: Cabbage\Core\Handler
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document_mapper'
            - '@cabbage.document_bulk_serializer'
            - '@cabbage.query_translator'
            - '@cabbage.query_router'
            - '@cabbage.result_extractor'
