services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.gateway:
        class: Cabbage\Core\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.document.mapper:
        class: Cabbage\Core\Document\Mapper
        arguments:
            - '@ezpublish.spi.persistence.location_handler'

    cabbage.document.router:
        class: Cabbage\Core\Document\Router

    cabbage.document.field.value_mapper.visitor.boolean:
        class: Cabbage\Core\Document\Field\ValueMapper\Visitor\Boolean

    cabbage.document.field.value_mapper.visitor.keyword:
        class: Cabbage\Core\Document\Field\ValueMapper\Visitor\Keyword

    cabbage.document.field.value_mapper:
        class: Cabbage\Core\Document\Field\ValueMapper
        arguments:
            -
                - '@cabbage.document.field.value_mapper.visitor.boolean'
                - '@cabbage.document.field.value_mapper.visitor.keyword'

    cabbage.document.field.name_generator:
        class: Cabbage\Core\Document\Field\NameGenerator

    cabbage.document.serializer:
        class: Cabbage\Core\Document\Serializer
        arguments:
            - '@cabbage.document.field.name_generator'
            - '@cabbage.document.field.value_mapper'

    cabbage.document.bulk_serializer:
        class: Cabbage\Core\Document\BulkSerializer
        arguments:
            - '@cabbage.document.router'
            - '@cabbage.document.serializer'

    cabbage.query_translator.criterion.visitor.custom_field:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\CustomField

    cabbage.query_translator.criterion.visitor.document_type:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\DocumentType

    cabbage.query_translator.criterion.converter:
        class: Cabbage\Core\Query\Translator\Criterion\Converter
        arguments:
            -
                - '@cabbage.query_translator.criterion.visitor.custom_field'
                - '@cabbage.query_translator.criterion.visitor.document_type'

    cabbage.query.translator:
        class: Cabbage\Core\Query\Translator
        arguments:
            - '@cabbage.query_translator.criterion.converter'

    cabbage.query.router:
        class: Cabbage\Core\Query\Router

    cabbage.result_extractor:
        class: Cabbage\Core\ResultExtractor

    cabbage.handler:
        class: Cabbage\Core\Handler
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document.mapper'
            - '@cabbage.document.bulk_serializer'
            - '@cabbage.query.translator'
            - '@cabbage.query.router'
            - '@cabbage.result_extractor'
