parameters:
    cabbage.field.name_generator.type_suffix_map:
        boolean: boolean
        keyword: keyword

services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.gateway:
        class: Cabbage\Core\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.field_type.data_mapper.checkbox:
        class: Cabbage\Core\FieldType\DataMapper\Checkbox

    cabbage.field_type.data_mapper.text_line:
        class: Cabbage\Core\FieldType\DataMapper\TextLine

    cabbage.field_type.data_mapper_registry:
        class: Cabbage\Core\FieldType\DataMapperRegistry
        arguments:
            -
                ezboolean: '@cabbage.field_type.data_mapper.checkbox'
                ezstring: '@cabbage.field_type.data_mapper.text_line'

    cabbage.document.mapper.content_field.name_generator:
        class: Cabbage\Core\Document\Mapper\ContentField\NameGenerator

    cabbage.document.mapper.content_field.mapper:
        class: Cabbage\Core\Document\Mapper\ContentField\Mapper
        arguments:
            - '@cabbage.field_type.data_mapper_registry'
            - '@cabbage.document.mapper.content_field.name_generator'

    cabbage.document.id_generator:
        class: Cabbage\Core\Document\Mapper\IdGenerator

    cabbage.document.mapper:
        class: Cabbage\Core\Document\Mapper
        arguments:
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@cabbage.document.mapper.content_field.mapper'
            - '@cabbage.document.id_generator'

    cabbage.document.bulk_serializer.router:
        class: Cabbage\Core\Document\BulkSerializer\Router

    cabbage.document.field.value_mapper.visitor.boolean:
        class: Cabbage\Core\Document\BulkSerializer\Field\ValueMapper\Visitor\Boolean

    cabbage.document.field.value_mapper.visitor.keyword:
        class: Cabbage\Core\Document\BulkSerializer\Field\ValueMapper\Visitor\Keyword

    cabbage.document.field.value_mapper:
        class: Cabbage\Core\Document\BulkSerializer\Field\ValueMapper
        arguments:
            -
                - '@cabbage.document.field.value_mapper.visitor.boolean'
                - '@cabbage.document.field.value_mapper.visitor.keyword'

    cabbage.document.field.typed_name_generator:
        class: Cabbage\Core\Document\BulkSerializer\Field\TypedNameGenerator
        arguments:
            - '%cabbage.field.name_generator.type_suffix_map%'

    cabbage.document.bulk_serializer.serializer:
        class: Cabbage\Core\Document\BulkSerializer\Serializer
        arguments:
            - '@cabbage.document.field.typed_name_generator'
            - '@cabbage.document.field.value_mapper'

    cabbage.document.bulk_serializer:
        class: Cabbage\Core\Document\BulkSerializer
        arguments:
            - '@cabbage.document.bulk_serializer.router'
            - '@cabbage.document.bulk_serializer.serializer'

    cabbage.query_translator.criterion.visitor.custom_field:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\RawField

    cabbage.query_translator.criterion.visitor.document_type:
        class: Cabbage\Core\Query\Translator\Criterion\Visitor\DocumentType

    cabbage.query_translator.criterion.converter:
        class: Cabbage\Core\Query\Translator\Criterion\Converter
        arguments:
            -
                - '@cabbage.query_translator.criterion.visitor.custom_field'
                - '@cabbage.query_translator.criterion.visitor.document_type'

    cabbage.query.translator:
        class: Cabbage\Core\Query\Translator
        arguments:
            - '@cabbage.query_translator.criterion.converter'

    cabbage.query.router:
        class: Cabbage\Core\Query\Router

    cabbage.result_extractor:
        class: Cabbage\Core\ResultExtractor

    cabbage.handler:
        class: Cabbage\Core\Handler
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document.mapper'
            - '@cabbage.document.bulk_serializer'
            - '@cabbage.query.translator'
            - '@cabbage.query.router'
            - '@cabbage.result_extractor'
