parameters:

services:
    cabbage.node.default:
        class: Cabbage\SPI\Node
        factory: Cabbage\SPI\Node::fromDsn
        arguments:
            - 'http://localhost:9200'

    cabbage.index.default:
        class: Cabbage\SPI\Index
        arguments:
            - '@cabbage.node.default'
            - 'index'

    cabbage.cluster.configuration:
        class: Cabbage\Core\Cluster\Configuration
        arguments:
            -
                - '@cabbage.node.default'
            - []
            - ~
            - '@cabbage.index.default'

    cabbage.cluster.coordinating_node_selector:
        class: Cabbage\Core\Cluster\CoordinatingNodeSelector
        arguments:
            - '@cabbage.cluster.configuration'
            -
    cabbage.cluster:
        class: Cabbage\Core\Cluster
        arguments:
            - '@cabbage.cluster.coordinating_node_selector'
