parameters:
    cabbage.document.field.type_suffix_map:
        boolean: boolean
        keyword: keyword
        identifier: identifier

services:
    cabbage.document.field_mapper.content_field.name_generator:
        class: Cabbage\Core\Indexer\Document\FieldMapper\ContentField\NameGenerator

    cabbage.document.field_mapper.content_field.mapper:
        class: Cabbage\Core\Indexer\Document\FieldMapper\ContentField\Mapper
        arguments:
            - '@cabbage.field_type.data_mapper_registry'
            - '@cabbage.document.field_mapper.content_field.name_generator'

    cabbage.document.id_generator:
        class: Cabbage\Core\Indexer\Document\IdGenerator

    cabbage.document.builder:
        class: Cabbage\Core\Indexer\Document\Builder
        arguments:
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@cabbage.document.field_mapper.content_field.mapper'
            - '@cabbage.document.id_generator'

    cabbage.document.destination_resolver:
        class: Cabbage\Core\Indexer\Document\DestinationResolver
        arguments:
            - '@cabbage.cluster'

    cabbage.document.serializer.field_value_mapper.visitor.boolean:
        class: Cabbage\Core\Indexer\Document\Serializer\FieldValueMapper\Visitor\Boolean

    cabbage.document.serializer.field_value_mapper.visitor.keyword:
        class: Cabbage\Core\Indexer\Document\Serializer\FieldValueMapper\Visitor\Keyword

    cabbage.document.serializer.field_value_mapper.visitor.identifier:
        class: Cabbage\Core\Indexer\Document\Serializer\FieldValueMapper\Visitor\Identifier

    cabbage.document.serializer.field_value_mapper:
        class: Cabbage\Core\Indexer\Document\Serializer\FieldValueMapper
        arguments:
            -
                - '@cabbage.document.serializer.field_value_mapper.visitor.boolean'
                - '@cabbage.document.serializer.field_value_mapper.visitor.keyword'
                - '@cabbage.document.serializer.field_value_mapper.visitor.identifier'

    cabbage.document.serializer.typed_field_name_generator:
        class: Cabbage\Core\Indexer\Document\Serializer\TypedFieldNameGenerator
        arguments:
            - '%cabbage.document.field.type_suffix_map%'

    cabbage.document.serializer:
        class: Cabbage\Core\Indexer\Document\Serializer
        arguments:
            - '@cabbage.document.serializer.typed_field_name_generator'
            - '@cabbage.document.serializer.field_value_mapper'

    cabbage.indexer.gateway:
        class: Cabbage\Core\Indexer\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.indexer:
        class: Cabbage\Core\Indexer
        arguments:
            - '@cabbage.indexer.gateway'
            - '@cabbage.document.builder'
            - '@cabbage.document.serializer'
            - '@cabbage.document.destination_resolver'
