parameters:
    cabbage.document.field.type_suffix_map:
        boolean: boolean
        keyword: keyword
        identifier: identifier

services:
    cabbage.indexer.field_builder.translation.content.content_field_name_generator:
        class: Cabbage\Core\Indexer\FieldBuilders\TranslationContent\ContentFieldNameGenerator

    cabbage.indexer.field_builder.common:
        class: Cabbage\Core\Indexer\FieldBuilders\Common\Aggregate
        arguments:
            - []

    cabbage.indexer.field_builder.content:
        class: Cabbage\Core\Indexer\FieldBuilders\Content\Aggregate
        arguments:
            - []

    cabbage.indexer.field_builder.location:
        class: Cabbage\Core\Indexer\FieldBuilders\Location\Aggregate
        arguments:
            - []

    cabbage.indexer.field_builder.translation_content.content_fields:
        class: Cabbage\Core\Indexer\FieldBuilders\TranslationContent\ContentFields
        arguments:
            - '@cabbage.field_type.data_mapper_registry'
            - '@cabbage.indexer.field_builder.translation.content.content_field_name_generator'

    cabbage.indexer.field_builder.translation_content:
        class: Cabbage\Core\Indexer\FieldBuilders\TranslationContent\Aggregate
        arguments:
            -
                - '@cabbage.indexer.field_builder.translation_content.content_fields'

    cabbage.indexer.field_builder.translation_location:
        class: Cabbage\Core\Indexer\FieldBuilders\TranslationLocation\Aggregate
        arguments:
            - []

    cabbage.indexer.document_id_generator:
        class: Cabbage\Core\Indexer\DocumentIdGenerator

    cabbage.indexer.document_builder:
        class: Cabbage\Core\Indexer\DocumentBuilder
        arguments:
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@cabbage.indexer.field_builder.common'
            - '@cabbage.indexer.field_builder.content'
            - '@cabbage.indexer.field_builder.location'
            - '@cabbage.indexer.field_builder.translation_content'
            - '@cabbage.indexer.field_builder.translation_location'
            - '@cabbage.indexer.document_id_generator'

    cabbage.indexer.destination_resolver:
        class: Cabbage\Core\Indexer\DestinationResolver
        arguments:
            - '@cabbage.cluster'

    cabbage.indexer.document_serializer.field_value_mapper.visitor.boolean:
        class: Cabbage\Core\Indexer\DocumentSerializer\FieldValueMapper\Visitor\Boolean

    cabbage.indexer.document_serializer.field_value_mapper.visitor.keyword:
        class: Cabbage\Core\Indexer\DocumentSerializer\FieldValueMapper\Visitor\Keyword

    cabbage.indexer.document_serializer.field_value_mapper.visitor.identifier:
        class: Cabbage\Core\Indexer\DocumentSerializer\FieldValueMapper\Visitor\Identifier

    cabbage.indexer.document_serializer.field_value_mapper:
        class: Cabbage\Core\Indexer\DocumentSerializer\FieldValueMapper
        arguments:
            -
                - '@cabbage.indexer.document_serializer.field_value_mapper.visitor.boolean'
                - '@cabbage.indexer.document_serializer.field_value_mapper.visitor.keyword'
                - '@cabbage.indexer.document_serializer.field_value_mapper.visitor.identifier'

    cabbage.indexer.document_serializer.typed_field_name_generator:
        class: Cabbage\Core\Indexer\DocumentSerializer\TypedFieldNameGenerator
        arguments:
            - '%cabbage.document.field.type_suffix_map%'

    cabbage.indexer.document_serializer:
        class: Cabbage\Core\Indexer\DocumentSerializer
        arguments:
            - '@cabbage.indexer.document_serializer.typed_field_name_generator'
            - '@cabbage.indexer.document_serializer.field_value_mapper'

    cabbage.indexer.gateway:
        class: Cabbage\Core\Indexer\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.indexer:
        class: Cabbage\Core\Indexer
        arguments:
            - '@cabbage.indexer.gateway'
            - '@cabbage.indexer.document_builder'
            - '@cabbage.indexer.document_serializer'
            - '@cabbage.indexer.destination_resolver'
