imports:
    - { resource: searcher/criterion_converters.yml }

parameters:

services:
    cabbage.searcher.query_translator:
        class: Cabbage\Core\Searcher\QueryTranslator
        arguments:
            - '@cabbage.searcher.query_translator.criterion.converter'

    cabbage.searcher.language_filter_indices_resolver:
        class: Cabbage\Core\Searcher\LanguageFilterIndicesResolver
        arguments:
            - '@cabbage.cluster.configuration'

    cabbage.searcher.result_extractor:
        class: Cabbage\Core\Searcher\ResultExtractor

    cabbage.searcher.gateway:
        class: Cabbage\Core\Searcher\Gateway
        arguments:
            - '@cabbage.http_client'

    cabbage.searcher:
        class: Cabbage\Core\Searcher
        arguments:
            - '@cabbage.searcher.gateway'
            - '@cabbage.searcher.language_filter_indices_resolver'
            - '@cabbage.searcher.query_translator'
            - '@cabbage.searcher.result_extractor'
            - '@cabbage.cluster'
