parameters:

services:
    cabbage.query_translator.criterion.visitor.content_id:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\ContentId

    cabbage.query_translator.criterion.visitor.document_type:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\DocumentType

    cabbage.query_translator.criterion.visitor.match_all:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\MatchAll

    cabbage.query_translator.criterion.visitor.match_none:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\MatchNone

    cabbage.query_translator.criterion.visitor.raw_field:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\RawField

    cabbage.query_translator.criterion.converter:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Converter
        arguments:
            -
                - '@cabbage.query_translator.criterion.visitor.content_id'
                - '@cabbage.query_translator.criterion.visitor.document_type'
                - '@cabbage.query_translator.criterion.visitor.match_all'
                - '@cabbage.query_translator.criterion.visitor.match_none'
                - '@cabbage.query_translator.criterion.visitor.raw_field'

    cabbage.query.translator:
        class: Cabbage\Core\Searcher\Query\Translator
        arguments:
            - '@cabbage.query_translator.criterion.converter'

    cabbage.query.target_resolver:
        class: Cabbage\Core\Searcher\Query\TargetResolver
        arguments:
            - '@cabbage.cluster'

    cabbage.result_extractor:
        class: Cabbage\Core\Searcher\ResultExtractor

    cabbage.searcher.gateway:
        class: Cabbage\Core\Searcher\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.searcher:
        class: Cabbage\Core\Searcher
        arguments:
            - '@cabbage.searcher.gateway'
            - '@cabbage.query.translator'
            - '@cabbage.query.target_resolver'
            - '@cabbage.result_extractor'
