imports:
    - { resource: cluster.yml }
    - { resource: field_type.yml }
    - { resource: indexer.yml }
    - { resource: searcher.yml }
    - { resource: slots.yml }

parameters:
    cabbage.field.name_generator.type_suffix_map:
        boolean: boolean
        keyword: keyword
        identifier: identifier

services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.engine:
        class: Cabbage\Core\Engine
        arguments:
            - '@cabbage.indexer'
            - '@cabbage.searcher'

    ezpublish.spi.search_engine:
        alias: cabbage.engine

    ezpublish.signalslot.signal_dispatcher.factory:
        class: eZ\Publish\Core\Base\Container\ApiLoader\SignalSlot\SignalDispatcherFactory
        arguments:
            - '%ezpublish.signalslot.signal_dispatcher.class%'
            - 'cabbage'

    cabbage.index_registry:
        class: Cabbage\Core\IndexRegistry
        arguments:
            -
                default: '@cabbage.index.default'
