imports:
    - { resource: cluster.yml }
    - { resource: field_type.yml }
    - { resource: field_builders.yml }
    - { resource: indexer.yml }
    - { resource: searcher.yml }
    - { resource: slots.yml }

parameters:

services:
    cabbage.http_client:
        class: Cabbage\Core\HttpClient\Client

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http_client'

    cabbage.engine:
        class: Cabbage\Core\Engine
        arguments:
            - '@cabbage.indexer'
            - '@cabbage.searcher'

    ezpublish.spi.search_engine:
        alias: cabbage.engine

    ezpublish.signalslot.signal_dispatcher.factory:
        class: eZ\Publish\Core\Base\Container\ApiLoader\SignalSlot\SignalDispatcherFactory
        arguments:
            - '%ezpublish.signalslot.signal_dispatcher.class%'
            - 'cabbage'
