imports:
    - { resource: slots.yml }

parameters:
    cabbage.field.name_generator.type_suffix_map:
        boolean: boolean
        keyword: keyword
        identifier: identifier

services:
    cabbage.http.client:
        class: Cabbage\Core\Http\Client

    cabbage.gateway:
        class: Cabbage\Core\Gateway
        arguments:
            - '@cabbage.http.client'

    cabbage.configurator:
        class: Cabbage\Core\Configurator
        arguments:
            - '@cabbage.http.client'

    cabbage.field_type.data_mapper.checkbox:
        class: Cabbage\Core\FieldType\DataMapper\Checkbox

    cabbage.field_type.data_mapper.text_line:
        class: Cabbage\Core\FieldType\DataMapper\TextLine

    cabbage.field_type.data_mapper.unmapped:
        class: Cabbage\Core\FieldType\DataMapper\Unmapped

    cabbage.field_type.data_mapper_registry:
        class: Cabbage\Core\FieldType\DataMapperRegistry
        arguments:
            -
                ezboolean: '@cabbage.field_type.data_mapper.checkbox'
                ezstring: '@cabbage.field_type.data_mapper.text_line'
                ezrichtext: '@cabbage.field_type.data_mapper.unmapped'
                ezpage: '@cabbage.field_type.data_mapper.unmapped'
                ezkeyword: '@cabbage.field_type.data_mapper.unmapped'
                ezinisetting: '@cabbage.field_type.data_mapper.unmapped'
                eztext: '@cabbage.field_type.data_mapper.unmapped'
                ezemail: '@cabbage.field_type.data_mapper.unmapped'
                ezuser: '@cabbage.field_type.data_mapper.unmapped'
                ezimage: '@cabbage.field_type.data_mapper.unmapped'
                ezpackage: '@cabbage.field_type.data_mapper.unmapped'
                ezurl: '@cabbage.field_type.data_mapper.unmapped'

    cabbage.document.mapper.content_field.name_generator:
        class: Cabbage\Core\Indexer\Document\Mapper\ContentField\NameGenerator

    cabbage.document.mapper.content_field.mapper:
        class: Cabbage\Core\Indexer\Document\Mapper\ContentField\Mapper
        arguments:
            - '@cabbage.field_type.data_mapper_registry'
            - '@cabbage.document.mapper.content_field.name_generator'

    cabbage.document.id_generator:
        class: Cabbage\Core\Indexer\Document\Mapper\IdGenerator

    cabbage.document.mapper:
        class: Cabbage\Core\Indexer\Document\Mapper
        arguments:
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@cabbage.document.mapper.content_field.mapper'
            - '@cabbage.document.id_generator'

    cabbage.document.destination_resolver:
        class: Cabbage\Core\Indexer\Document\DestinationResolver
        arguments:
            - '@cabbage.index_registry'

    cabbage.document.field.value_mapper.visitor.boolean:
        class: Cabbage\Core\Indexer\Document\Field\ValueMapper\Visitor\Boolean

    cabbage.document.field.value_mapper.visitor.keyword:
        class: Cabbage\Core\Indexer\Document\Field\ValueMapper\Visitor\Keyword

    cabbage.document.field.value_mapper.visitor.identifier:
        class: Cabbage\Core\Indexer\Document\Field\ValueMapper\Visitor\Identifier

    cabbage.document.field.value_mapper:
        class: Cabbage\Core\Indexer\Document\Field\ValueMapper
        arguments:
            -
                - '@cabbage.document.field.value_mapper.visitor.boolean'
                - '@cabbage.document.field.value_mapper.visitor.keyword'
                - '@cabbage.document.field.value_mapper.visitor.identifier'

    cabbage.document.field.typed_name_generator:
        class: Cabbage\Core\Indexer\Document\Field\TypedNameGenerator
        arguments:
            - '%cabbage.field.name_generator.type_suffix_map%'

    cabbage.document.serializer:
        class: Cabbage\Core\Indexer\Document\Serializer
        arguments:
            - '@cabbage.document.destination_resolver'
            - '@cabbage.document.field.typed_name_generator'
            - '@cabbage.document.field.value_mapper'

    cabbage.query_translator.criterion.visitor.content_id:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\ContentId

    cabbage.query_translator.criterion.visitor.document_type:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\DocumentType

    cabbage.query_translator.criterion.visitor.match_all:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\MatchAll

    cabbage.query_translator.criterion.visitor.match_none:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\MatchNone

    cabbage.query_translator.criterion.visitor.raw_field:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Visitor\RawField

    cabbage.query_translator.criterion.converter:
        class: Cabbage\Core\Searcher\Query\Translator\Criterion\Converter
        arguments:
            -
                - '@cabbage.query_translator.criterion.visitor.content_id'
                - '@cabbage.query_translator.criterion.visitor.document_type'
                - '@cabbage.query_translator.criterion.visitor.match_all'
                - '@cabbage.query_translator.criterion.visitor.match_none'
                - '@cabbage.query_translator.criterion.visitor.raw_field'

    cabbage.query.translator:
        class: Cabbage\Core\Searcher\Query\Translator
        arguments:
            - '@cabbage.query_translator.criterion.converter'

    cabbage.query.target_resolver:
        class: Cabbage\Core\Searcher\Query\TargetResolver
        arguments:
            - '@cabbage.index_registry'

    cabbage.result_extractor:
        class: Cabbage\Core\Searcher\ResultExtractor

    cabbage.indexer:
        class: Cabbage\Core\Indexer
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.document.mapper'
            - '@cabbage.document.serializer'

    cabbage.searcher:
        class: Cabbage\Core\Searcher
        arguments:
            - '@cabbage.gateway'
            - '@cabbage.query.translator'
            - '@cabbage.query.target_resolver'
            - '@cabbage.result_extractor'

    cabbage.handler:
        class: Cabbage\Core\Handler
        arguments:
            - '@cabbage.indexer'
            - '@cabbage.searcher'

    ezpublish.spi.search_engine:
        alias: cabbage.handler

    ezpublish.signalslot.signal_dispatcher.factory:
        class: eZ\Publish\Core\Base\Container\ApiLoader\SignalSlot\SignalDispatcherFactory
        arguments:
            - '%ezpublish.signalslot.signal_dispatcher.class%'
            - 'cabbage'

    cabbage.node.default:
        class: Cabbage\SPI\Node
        factory: Cabbage\SPI\Node::fromDsn
        arguments:
            - 'http://localhost:9200'

    cabbage.index.default:
        class: Cabbage\SPI\Index
        arguments:
            - '@cabbage.node.default'
            - 'index'

    cabbage.index_registry:
        class: Cabbage\Core\IndexRegistry
        arguments:
            -
                default: '@cabbage.index.default'
